#!/usr/bin/env bash
set -euo pipefail

# Generated by TheRock Test Agent. Do not edit artifacts or component sources.
# task_id=hipsparse-standard
# entrypoint_type=test_runner
# script=test_runner.py
cd /home/zs/TheRock

export AMDGPU_FAMILIES=gfx1151
export HIP_PATH=/home/zs/TheRock/output-linux-portable/build/dist/rocm
export LD_LIBRARY_PATH=/home/zs/TheRock/output-linux-portable/build/dist/rocm/lib:/home/zs/TheRock/output-linux-portable/build/dist/rocm/lib64
export OUTPUT_ARTIFACTS_DIR=/home/zs/TheRock/output-linux-portable/build/dist/rocm
export PATH=/home/zs/TheRock/runs/20260710_190554_105b10f6/sudo_askpass_bin:/home/zs/TheRock/output-linux-portable/build/dist/rocm/bin:/home/zs/.bun/bin:/home/zs/.bun/bin:/home/zs/.nvm/versions/node/v24.18.0/bin:/home/zs/.opencode/bin:/home/zs/.mimocode/bin:/home/zs/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/zs/.local/bin:/home/zs/.local/bin
export ROCM_PATH=/home/zs/TheRock/output-linux-portable/build/dist/rocm
export SHARD_INDEX=1
export TEST_COMPONENT=hipsparse
export TEST_TYPE=standard
export THEROCK_AMDGPU_FAMILIES=gfx1151
export THEROCK_AMDGPU_TARGETS=gfx1151
export THEROCK_BIN_DIR=/home/zs/TheRock/output-linux-portable/build/dist/rocm/bin
export TOTAL_SHARDS=1

exec python3 /home/zs/TheRock/build_tools/github_actions/test_executable_scripts/test_runner.py
