from __future__ import annotations

import os
import shlex
import subprocess
import time
from pathlib import Path
from typing import Any

from .artifacts import discover_therock_repo
from .audit import append_activity
from .audit import append_jsonl
from .audit import append_wrapper_audit
from .audit import ensure_dir
from .audit import now_iso
from .audit import safe_env_value
from .classifier import detect_failure_summary
from .classifier import detect_path_hardcode
from .config import SENSITIVE_ENV_NAMES
from .config import load_component_env_index
from .entrypoint import build_task_env
from .entrypoint import expand_template
from .entrypoint import resolve_entrypoint
from .entrypoint import task_context
from .preflight import check_task_preflight
from .state import save_state


def changed_env_values(env: dict[str, str]) -> dict[str, str]:
    changes: dict[str, str] = {}
    for key, value in sorted(env.items()):
        if key in SENSITIVE_ENV_NAMES or ("PASSWORD" in key.upper()) or ("TOKEN" in key.upper()):
            continue
        if os.environ.get(key) != value:
            changes[key] = value
    return changes


def write_execution_wrapper(
    state: dict[str, Any],
    task: dict[str, Any],
    round_no: int,
    command: list[str],
    cwd: str,
    env: dict[str, str],
    entrypoint_metadata: dict[str, Any],
) -> tuple[Path, dict[str, Any]]:
    wrappers_dir = Path(state["meta"]["output_dir"]) / "wrappers"
    ensure_dir(wrappers_dir)
    wrapper_path = wrappers_dir / f"{task['task_id']}.round{round_no}.sh"
    env_changes = changed_env_values(env)

    lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "",
        "# Generated by TheRock Test Agent. Do not edit artifacts or component sources.",
        f"# task_id={task['task_id']}",
        f"# entrypoint_type={entrypoint_metadata.get('entrypoint_type', '')}",
        f"# script={entrypoint_metadata.get('script', '')}",
        f"cd {shlex.quote(cwd)}",
        "",
    ]
    for key, value in env_changes.items():
        lines.append(f"export {key}={shlex.quote(value)}")
    lines.extend(["", "exec " + " ".join(shlex.quote(item) for item in command)])

    wrapper_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    wrapper_path.chmod(0o755)

    details = {
        "wrapper_path": str(wrapper_path),
        "cwd": cwd,
        "command": " ".join(command),
        "env_changes": {key: safe_env_value(key, value) for key, value in env_changes.items()},
        "entrypoint": entrypoint_metadata,
        "policy": "wrapper_only_no_artifact_or_source_mutation",
    }
    return wrapper_path, details


def render_command(
    project_root: Path,
    state: dict[str, Any],
    task: dict[str, Any],
    round_no: int,
) -> list[str] | str:
    meta = state["meta"]
    mock_command = meta.get("mock_command")
    if mock_command:
        return mock_command.format(
            task_id=task["task_id"],
            component=task["component"],
            test_type=task["test_type"],
            round=round_no,
        )

    therock_repo = discover_therock_repo(project_root, str(meta.get("therock_repo_path") or ""))
    if not therock_repo:
        raise FileNotFoundError("缺少 TheRock 仓库路径，请传入 --therock-repo 或设置 THEROCK_REPO。")
    entrypoint = task.get("entrypoint") or resolve_entrypoint(
        load_component_env_index(Path(meta["component_env_index"])),
        task["component"],
        task["test_type"],
    )
    entrypoint_type = entrypoint.get("entrypoint_type", "test_runner")

    scripts_dir = therock_repo / "build_tools" / "github_actions" / "test_executable_scripts"
    if entrypoint_type == "test_runner":
        script_name = "test_runner.py"
    elif entrypoint_type == "dedicated_python":
        script_name = str(entrypoint.get("script") or "")
        if not script_name:
            raise FileNotFoundError(f"{task['component']} 缺少 dedicated_python script 配置。")
    else:
        raise FileNotFoundError(f"{task['component']} entrypoint_type={entrypoint_type} 不可执行。")

    script_path = scripts_dir / script_name
    if not script_path.is_file():
        raise FileNotFoundError(f"找不到 TheRock 测试脚本: {script_path}")

    context = task_context(state, task, entrypoint)
    command = ["python3", str(script_path)]
    for arg in entrypoint.get("cli_args", []):
        command.append(expand_template(str(arg), context))
    return command


def run_task(project_root: Path, state: dict[str, Any], task: dict[str, Any], round_no: int) -> dict[str, Any]:
    output_dir = Path(state["meta"]["output_dir"])
    logs_dir = output_dir / "logs"
    stdout_path = logs_dir / f"{task['task_id']}.round{round_no}.stdout.log"
    stderr_path = logs_dir / f"{task['task_id']}.round{round_no}.stderr.log"
    command_record: str
    original_command_record = ""
    wrapper_details: dict[str, Any] | None = None
    start = time.time()
    entrypoint = task.get("entrypoint") or resolve_entrypoint(
        load_component_env_index(Path(state["meta"]["component_env_index"])),
        task["component"],
        task["test_type"],
    )
    env, entrypoint_metadata = build_task_env(state, task, entrypoint)

    state["schedule"]["current_task"] = task["task_id"]
    save_state(state)
    append_activity(
        state,
        "task_start",
        {
            "task_id": task["task_id"],
            "round": round_no,
            "component": task["component"],
            "test_type": task["test_type"],
            "stdout_log": str(stdout_path),
            "stderr_log": str(stderr_path),
            "entrypoint": entrypoint_metadata,
        },
    )

    try:
        preflight_error = check_task_preflight(state, task, env, entrypoint_metadata)
        if preflight_error:
            command_record = "blocked before execution"
            return_code = 125
            status = "blocked"
            failure_summary = preflight_error
            stdout_path.write_text("", encoding="utf-8")
            stderr_path.write_text(preflight_error + "\n", encoding="utf-8")
        else:
            command = render_command(project_root, state, task, round_no)
            command_record = command if isinstance(command, str) else " ".join(command)
            cwd = (
                state["meta"]["build_root"]
                if isinstance(command, str)
                else str(discover_therock_repo(project_root, str(state["meta"].get("therock_repo_path") or "")) or state["meta"]["build_root"])
            )
            if isinstance(command, str):
                executable_command: str | list[str] = command
            else:
                wrapper_path, wrapper_details = write_execution_wrapper(
                    state,
                    task,
                    round_no,
                    command,
                    cwd,
                    env,
                    entrypoint_metadata,
                )
                original_command_record = command_record
                command_record = str(wrapper_path)
                executable_command = [str(wrapper_path)]
                append_wrapper_audit(
                    state,
                    {
                        "time": now_iso(),
                        "event": "wrapper_generated",
                        "task_id": task["task_id"],
                        "round": round_no,
                        **wrapper_details,
                    },
                )
                append_activity(
                    state,
                    "wrapper_generated",
                    {
                        "task_id": task["task_id"],
                        "round": round_no,
                        "wrapper_path": str(wrapper_path),
                        "env_change_keys": sorted(wrapper_details["env_changes"].keys()),
                        "policy": wrapper_details["policy"],
                    },
                )
            with stdout_path.open("w", encoding="utf-8") as stdout_handle, stderr_path.open("w", encoding="utf-8") as stderr_handle:
                if isinstance(executable_command, str):
                    proc = subprocess.run(
                        executable_command,
                        shell=True,
                        cwd=cwd,
                        env=env,
                        stdout=stdout_handle,
                        stderr=stderr_handle,
                        text=True,
                    )
                else:
                    proc = subprocess.run(
                        executable_command,
                        cwd=cwd,
                        env=os.environ.copy(),
                        stdout=stdout_handle,
                        stderr=stderr_handle,
                        text=True,
                    )
            return_code = proc.returncode
            status = "pass" if return_code == 0 else "fail"
            failure_summary = "" if status == "pass" else detect_failure_summary(stdout_path, stderr_path)
    except FileNotFoundError as exc:
        command_record = str(exc)
        return_code = 127
        status = "blocked"
        failure_summary = str(exc)
        stdout_path.write_text("", encoding="utf-8")
        stderr_path.write_text(str(exc) + "\n", encoding="utf-8")

    path_hardcode_detection = detect_path_hardcode(stdout_path, stderr_path)
    if path_hardcode_detection["detected"]:
        append_activity(
            state,
            "path_hardcode_detected",
            {
                "task_id": task["task_id"],
                "round": round_no,
                "categories": path_hardcode_detection["categories"],
                "matches": path_hardcode_detection["matches"],
                "policy": "detected_only_no_artifact_or_source_mutation",
            },
        )
        if status != "pass":
            first_match = path_hardcode_detection["matches"][0]
            failure_summary = f"{first_match['category']}: {first_match['line']}"

    duration = round(time.time() - start, 3)
    result = {
        "task_id": task["task_id"],
        "component": task["component"],
        "test_type": task["test_type"],
        "status": status,
        "return_code": return_code,
        "duration_seconds": duration,
        "stdout_log": str(stdout_path),
        "stderr_log": str(stderr_path),
        "failure_summary": failure_summary,
        "gpu_hang_risk": task.get("gpu_hang_risk", False),
        "entrypoint_type": entrypoint_metadata.get("entrypoint_type"),
        "script": entrypoint_metadata.get("script"),
        "test_component": entrypoint_metadata.get("test_component"),
        "env_profiles": entrypoint_metadata.get("env_profiles", []),
        "known_issue_category": entrypoint_metadata.get("known_issue_category"),
        "retry_policy": entrypoint_metadata.get("retry_policy"),
        "timeout_hint_seconds": entrypoint_metadata.get("timeout_hint_seconds"),
        "preflight_python_modules": entrypoint_metadata.get("preflight_python_modules", []),
        "round": round_no,
        "command": command_record,
        "original_command": original_command_record,
        "wrapper_path": wrapper_details["wrapper_path"] if wrapper_details else "",
        "wrapper_env_change_keys": sorted(wrapper_details["env_changes"].keys()) if wrapper_details else [],
        "path_hardcode_detection": path_hardcode_detection,
        "finished_at": now_iso(),
    }

    state["results"]["task_results"][task["task_id"]] = result
    state["schedule"]["current_task"] = None
    save_state(state)

    append_jsonl(
        Path(state["meta"]["output_dir"]) / "tool_calls.jsonl",
        {
            "time": now_iso(),
            "tool": "shell",
            "task_id": task["task_id"],
            "command": command_record,
            "original_command": original_command_record,
            "wrapper_path": wrapper_details["wrapper_path"] if wrapper_details else "",
            "wrapper_env_change_keys": sorted(wrapper_details["env_changes"].keys()) if wrapper_details else [],
            "path_hardcode_detection": path_hardcode_detection,
            "return_code": return_code,
            "duration_seconds": duration,
            "status": status,
            "entrypoint": entrypoint_metadata,
        },
    )
    append_activity(
        state,
        "task_end",
        {
            "task_id": task["task_id"],
            "round": round_no,
            "command": command_record,
            "return_code": return_code,
            "duration_seconds": duration,
            "status": status,
            "stdout_log": str(stdout_path),
            "stderr_log": str(stderr_path),
            "wrapper_path": wrapper_details["wrapper_path"] if wrapper_details else "",
            "path_hardcode_detection": path_hardcode_detection,
        },
    )
    return result
